language: node_js
node_js:
  - "10.15.2"
script:
  - echo "Deploying"
install:
  - npm install -g firebase-tools
  - npm install -g @vue/cli@latest
  - npm install
after_success:  
  - npm run build
  - firebase deploy --token $FKEY

